kind: pipeline
type: docker
name: default
steps:
  - name: build_switch_ai
    image: docker:latest
    commands:
      - docker build -t switch-ai:${DRONE_COMMIT_SHA:0:8} .
      - docker tag switch-ai:${DRONE_COMMIT_SHA:0:8} switch-ai:latest
  - name: deploy
    image: docker/compose:1.29.2
    environment:
      PORT:
        from_secret: PORT
    commands:
      # - docker-compose down
      - docker-compose up --no-deps -d
trigger:
  branch:
    - main
  event:
    - push
