kind: pipeline
type: docker
name: default
steps:
  - name: build_switch_ai
    image: docker:latest
    privileged: true
    commands:
      - docker build -t switch-ai:${DRONE_COMMIT_SHA:0:8} .
      - docker tag switch-ai:${DRONE_COMMIT_SHA:0:8} switch-ai:latest
  - name: deploy_staging
    image: docker/compose:1.29.2
    privileged: true
    environment:
      PORT:
        from_secret: PORT
    commands:
      - docker-compose down switch-ai || true
      - docker-compose up -d --force-recreate switch-ai
      - docker-compose ps
      - docker image prune -f
  - name: check_logs
    image: docker:latest
    commands:
      - sleep 10
      - docker-compose logs switch-ai
    when:
      status:
        - success
        - failure
trigger:
  branch:
    - main
  event:
    - push
